### PR TITLE
Add to releases page

### PR DESCRIPTION
**Pull request by theMackabu**
The DMG has been added @jaywcjlove !

### CODE REVIEW

**Comment by jaywcjlove** [comment]
@sajjaadf It can be downloaded here. Didn't you find the place to download?
image

**Comment by jaywcjlove** [comment]
@sajjaadf  what is this?
image

**Comment by theMackabu** [comment]
It is when gatekeeper does not like to run Undefined apps

**Comment by sajjaadf** [comment]
Undefined!

**Comment by theMackabu** [comment]
Without disabling system Protection

**Comment by theMackabu** [comment]
It is a small python bash script

**Comment by theMackabu** [comment]
That version of AMAC won't work anymore

**Comment by theMackabu** [comment]
Screen Shot 2019-04-12 at 11 54 26 AM

**Comment by theMackabu** [comment]
But the one with gatekeeper exception will work

**Comment by theMackabu** [comment]
[mp4.zip](https://github.com/jaywcjlove/amac/files/3074811/mp4.zip)
Here is the video

**Comment by jaywcjlove** [comment]
@sajjaadf Thx! I still want to use a regular solution. #5

**Pull request closed without merging**
